name: simanap_mobile
description: Sebuah project membuat SIMANAP Mobile.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  english_words: ^4.0.0
  flutter:
    sdk: flutter
  flutter_lorem: ^2.0.0
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
