name: simanap_mobile
description: Sebuah project membuat web SIMANAP menjadi Mobile.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  english_words: ^4.0.0
  flutter:
    sdk: flutter
  flutter_lorem: ^2.0.0
  get: ^4.6.6
  http: ^1.1.0
  url_launcher: ^6.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/images/
    - assets/icon/

#Settings Font
fonts:
    - family: Staatliches
      fonts:
        - asset: fonts/Staatliches-Regular.ttf
    - family: Oxygen
      fonts:
        - asset: fonts/Oxygen-Regular.ttf

#Settings Icon
#flutter pub get
#dart pub run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/playstore_kuning.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
